chore: refresh (#389)

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,19 +1,23 @@
 ---
-name: main
+name: Main
 
 'on':
   pull_request:
     types: [opened, ready_for_review, reopened, synchronize]
   push:
-    branches: [main, 'renovate/**']
+    branches: [main]
   workflow_dispatch:
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
-  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
+  cancel-in-progress: true
 
 permissions:
   contents: read
+
+defaults:
+  run:
+    shell: 'bash -Eeuo pipefail {0}'
 
 jobs:
   build:
@@ -23,31 +27,39 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: Setup Node.js
-        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
+      - id: configure-cache
+        name: Configure cache
+        env:
+          # This must be updated if the pnpm store path changes
+          PNPM_SETUP_STORE_PATH: ~/setup-pnpm/node_modules/.bin/store/v3
+        run: |
+          pnpm_store_path="$PNPM_SETUP_STORE_PATH"
+          if [ `which pnpm` ]; then
+            pnpm_store_path="$(pnpm store path --silent)"
+          fi
+          if [ -z "pnpm_store_path" ]; then
+            echo "Failed to get pnpm store path"
+            exit 1
+          fi
+          mkdir -p "pnpm_store_path" || exit 1
+          echo "path=$pnpm_store_path" >> $GITHUB_OUTPUT
+          year_month=$(date -u '+%Y%m')
+          base_key="${{ runner.os }}-pnpm-cache-v${year_month}"
+          echo "key=${base_key}-${{ hashFiles('**/pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT
+          echo "restore-keys=${base_key}-" >> $GITHUB_OUTPUT
+
+      - name: Cache pnpm store
+        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
         with:
-          node-version-file: '.node-version'
+          key: ${{ steps.configure-cache.outputs.key }}
+          path: ${{ steps.configure-cache.outputs.path }}
+          restore-keys: ${{ steps.configure-cache.outputs.restore-keys }}
 
       - name: Setup pnpm
         uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
-
-      - id: pnpm-store
-        name: Get pnpm store directory
-        run: |
-          echo "path=$(pnpm store path)" >> $GITHUB_OUTPUT
-        shell: bash
-
-      - id: pnpm-cache
-        name: Set up pnpm cache
-        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
         with:
-          path: ${{ steps.pnpm-store.outputs.path }}
-          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-pnpm-
-
-      - name: Install dependencies
-        run: pnpm install --frozen-lockfile
+          run_install: |
+            - args: [--frozen-lockfile, --prefer-offline, --loglevel, error]
 
       - name: Run Prettier
         run: pnpm run check-format
